name: Build and Release Tauri App

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-latest' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' 

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.os == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install frontend dependencies
        run: npm install 
        
      - name: Build Tauri App
        run: npm run tauri build
      
      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-app-${{ matrix.os }}
          path: |
           ${{ matrix.os == 'macos-latest' && 'src-tauri/target/release/bundle/macos/*' || 'src-tauri/target/release/bundle/deb/*' }} 
